### ISSUE TITLE
ex 8.5

### ISSUE THREAD

**Issue by luigift** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#22]
In exercise 8.5, I believe that stochastic environments refers to stochastic state transition as well as reward. Thus, the model table should represent **p(s', r|s, a)** and not only **p(r| s, s', a)**, creating a *distribution model* rather than a *sample model*. When queried the model would generate sample transitions following **p(s', r | s, a)**.

I believe that in order to cope with changing environments some sort of *exploratory reward* should be given following the intuition of Dyna-Q+. Decaying experience would take time to shift the estimate of Q.

**Comment by LyWangPX** [comment]
Thanks for opening the issue. I am glad to hear your opinions. You are right about the stochastic though not changing condition, but let's dig it little bit further.

First, I do believe my anwser was in a rush and was not good.After careful rethinking, I believe the true question the author want to ask is indeed about schotastic AND changing. The question is letting us to rethink the step(e) in Dyna-Q even if it has been updated to Dyna-Q+. Here is my thoughts:

Let's review first. In a deterministic changing environment like blocking maze, we know Dyna-Q can detect worse condition by rewriting the model in step (e) but fail to notice better ones. Dyan-Q+ exploratory trick can help to find better path, and rewrite the model in step(e), too.  

However, when the environment is stochastic, we have to change (e) to keep counting possibilities on (s, s', a, r) tuple. When meeting changes of environemnt, methods have to figure out first if the changed rewards are due to chances. Of course we can add the new changes into the model and the percentage of new situation will grow. But, imagine an agent that runs too many step in the old environment, it will then be hard to learn the new one: any changes of reward or states will be treated as extremely unlikely event in the planning stage unless we spend long enough time. 

Thus, I think the experience decay would play an essential rule here. By only keeping a fixed amount, C, records in model of each state s, the update of model would be much faster. Most importantly, old records will be replaced entirely after C encounters from state s.

Let me conclude by rewriting the answer of stochastic part first. If the environment is stochasitc but deterministic, one should record every encounter from the game so far and add to model in order to keep the frequency distribution. Of course, the part you've mentioned should be changed. We need to make decision upon distribution and everything else should be consistent. However, if the environment is both stochasitc and changing, one should record nearest C records for each state the whole Model. (which could be thousands, I did not run an experiment on it yet though). With only recent C records of each state, local variance won't affect our distribution but fundamental changes will rewrite the whole model C records later.

What do you think about my new thoughts?  I would like to hear your ideas before closing the issue. 

Looking forward.

**Comment by LyWangPX** [comment]
I made multiple updates to my previous comment, hope it does not distub you too much.

**Comment by luigift** [comment]
I could understand everything, no worries!! Also, thank you for the thorough explanation!

I believe I was only concerned by changing rewards and was blind-sighted to changes in state transitions. In this case, I think that experience decay would continuously follow the to the non-stationary distribution **p(s', r|s, a)**

**Comment by luigift** [comment]
I'm sorry I mistakenly closed the issue

**Comment by LyWangPX** [comment]
That's OK. Please share your mind if you wish. :)

**Comment by luigift** [comment]
I could understand everything, no worries!! Also, thank you for the thorough explanation!

I just want to make a correction to my previous comment. It is not necessary to build a *distribution model* from experience, one equally build a *sample model* by storing all *s, a -> s', r* transitions and uniformly sample the model at step(f).

I stated that experience decay would take time to shift the estimate of **Q** towards **q*** for the new environment, but I'm actually concerned it would *never shift*. Epsilon-greedy action selection would bias the state visiting to its prior belief of the environment stored in Q and non-greedy actions would be improbable to achieve states with low Q-value.

Let's forget about continuously changing environments for a second and focus on the **shortcut maze**. The core idea of experience decay is to erase experience from the previous environment.  The most efficient experience forgetting decay would be to clear all model experience at the same time the environment changes (*step = 1000*). However, Q keeps its values. What happens is that in step(b) the agent will *always* take the *left path* and only states among the way will be stored in step(e) - some other states that where arrived by non-greedy actions. We need a way to make the Q-function revaluate its beliefs.

I believe the problem the author wants us to think about is:
> Even if we use "reward bonus", the probability of sampling improbable transitions from the old environment from the *sample model* (or the importance of this transition in a *distribution model*) would be very low or even close to zero. Thus, we need to some sort of "probability bonus" alongside with "reward bonus" to make sure we re-estimate its Q-value.

What do you think?

**Comment by LyWangPX** [comment]
Execellent Explanation. I think we are all agreeing that we need a way to change Q efficiently under worse and better maze condition, but also not to incur any instability. (because rewards can be just bad luck) 

You are definitely right that we need Dyna_Q+'s exploration. I am just so curious about why the author just ask DynaQ not DynaQ+. It made me think that he is not asking us the modification not out of the bound of DynaQ. That is, we deal with BETTER situation as the flaw of nature of DynaQ. What DynaQ still can, is to deal with WORSE situation. That is why I incline to only talk about blocking Maze. In that case, an experience decay will work.

If we extend the talk to the area of what Dyna_Q+ can be imporved, the discussion we have so far are indeed very valuable.

**Comment by LyWangPX** [comment]
My suggestion would be include the discussion of both dynaQ and dynaQ+ into the answer. It is a valuable discussion any way. If you agree with it, I will close the issue and combining our thoughts.

**Comment by luigift** [comment]
Interesting! Experience decay would actually help in the **blocking maze** I haven't seen that before, thank you.

I think the reason why the author talked about Dyna-Q was to guide the reader step-by-step in formulating the answer. Below is my understanding of the authors' intention:

> How might the tabular Dyna-Q algorithm shown on page 164 be modified
to handle stochastic environments?

Authors' intention: Ignore all degenerate cases such as changing environments, take the simplest algorithm and adapt for stochastic environments.

Answer: Store all transitions in step(e) to the model memory and uniformly sample from the model memory. 

> How might this modification perform poorly on changing environments such as considered in this section?

Authors' intention: extrapolate worst and better case from deterministic problem to stochastic

Answer: The stochastic Dyna-Q would cope with worst scenarios, but would keep visiting the same approximate trajectories due to learned Q-values

> How could the algorithm be modified to handle stochastic environments and changing environments?

Intention: You solved stochastic environments and understand the problem with changing environments. Now whats the solution?

Answer: "reward bonus"+ "probability bonus", since Dyna-Q+ wouldn't work. So it's not a question of improving Dyna-Q+. It is a question os how implementing Dyna-Q+ for it to *over evaluate* a previous q(s,a) with low reward.

Do you agree with this perspective?

**Comment by LyWangPX** [comment]
Brilliant. I totally agree with your thought now.

I will update the answer along with the finished Chapter 12 next week.

It's nice to have a talk with you. Please feel free to give any further feedbacks on any other parts of the book.

**Comment by luigift** [comment]
If you want to open a pull request for me to review. That's fine by me!
