### ISSUE TITLE
Question 3.22

### ISSUE THREAD

**Issue by openerror** [LyWangPX/Reinforcement-Learning-2nd-Edition-by-Sutton-Exercise-Solutions#42]
Numerical error: when gamma = 0.9, v_right = 9.5 and v_left = 5.3, rounded to two significant figures. The former sums over odd powers of gamma, the latter even powers.

Might also want to check gamma = 0.5

**Comment by LyWangPX** [comment]
Thanks for your response.

The implicit point I want to make it if in the initial round you find an optimal policy, it is equal to the overal optimal policy because everything we computed will be multiplied by gamma twice, which will not change the big or small relations. That is why I only compute the first round. It does not affect the final answer.

However, it will be more mathmatically correct if I write out the return formula directly and do the comparison. I will change it to a more formal form.

**Comment by LyWangPX** [comment]
Just updated. If you have further questions, please comment again.
